<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.3" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
		<PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Heresy.Core\Heresy.Core.csproj" />
		<ProjectReference Include="..\Heresy.Scripting\Heresy.Scripting.csproj" />
		<ProjectReference Include="..\Heresy.Render\Heresy.Render.csproj" />
		<ProjectReference Include="..\Heresy.Playback\Heresy.Playback.csproj" />
	</ItemGroup>

</Project>
