<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Description>Core song model, timing, sequencing contracts, and persistent definitions for Heresy.</Description>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

</Project>
