using System;
using System.Collections.Generic;

namespace Heresy.Core.Sequencing;

/// <summary>
/// A shared chronological mailbox for tempo sets generated by flattened
/// children but not yet reached by their parent. Events are never applied
/// when enqueued: the parent tick-timeline consumes them at their due time.
/// The initial integration supports sets at a fixed absolute time; time-warp
/// of a child's later boundary by other overlapping effects requires a
/// dedicated concurrent row scheduler.
/// </summary>
public sealed class DeferredTempoEventQueue
{
	public readonly record struct Change(TimeSpan At, double Tempo, long Order);
	private readonly List<Change> _pending = [];
	private long _order;

	public bool HasPending => _pending.Count != 0;

	public void Schedule(TimeSpan absoluteTime, double tempo)
	{
		if (absoluteTime < TimeSpan.Zero)
			throw new ArgumentOutOfRangeException(nameof(absoluteTime));
		if (!(tempo > 0.0) || !double.IsFinite(tempo))
			throw new ArgumentOutOfRangeException(nameof(tempo));
		_pending.Add(new Change(absoluteTime, tempo, _order++));
		_pending.Sort((a, b) =>
		{
			int comparison = a.At.CompareTo(b.At);
			return comparison != 0 ? comparison
				: a.Order.CompareTo(b.Order);
		});
	}

	public Change? Peek() => _pending.Count == 0 ? null : _pending[0];

	public Change Pop()
	{
		if (_pending.Count == 0)
			throw new InvalidOperationException("No deferred tempo changes remain.");
		Change change = _pending[0];
		_pending.RemoveAt(0);
		return change;
	}
}
